defaults:
  - paths
  - hydra
  - data
  - model
  - trainer
  - _self_

task_name: tiny-test

trainer_config:
  bf16: false
  per_device_train_batch_size: 16
  output_dir: ${paths.output_dir}
  report_to: tensorboard
  logging_dir: ${trainer_config.output_dir}/tb
  lr_scheduler_type: cosine
  learning_rate: 1e-4
  warmup_steps: 500
  max_steps: 10000
  save_steps: 1000
  label_smoothing_factor: 0.0

model_config:
  name: openai/whisper-tiny
  attn_implementation: eager